---
- name: update apt packages.
  become: true
  apt:
    update_cache: true

- name: upgrade packages
  become: true
  apt:
    upgrade: true

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true

- name: install dependencies
  become: true
  apt:
    name: ["nodejs", npm]
    state: latest
    update_cache: true

- name: install pm2
  become: true
  shell: |
    npm install pm2 -g
