version: 2.1

executors:
  aws_cli_executor:
    docker:
      - image: amazon/aws-cli #image for creating infrastructure on AWS

  python_alpine_executor:
    docker:
      - image: python:3.7-alpine3.16 #image for installing ansible and configuring infrastructure

  alpine_executor:
    docker:
      - image: alpine:latest

  nodejs_executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build-frontend:
    executor: nodejs_executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm i
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    executor: nodejs_executor
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            # Your code here
            cd backend
            npm i
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    executor: nodejs_executor
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys:
            - frontend-build
      # Your job code here
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm i
            npm run test

  test-backend:
    executor: nodejs_executor
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys:
            - backend-build
      # Your job code here
      - run:
          name: Test backend
          command: |
            cd backend
            npm i
            npm run test

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
